### PR TITLE
A bunch of little enhancements

### LINKED ISSUE #3: Maximise value from stacktraces
Investigate what we can do to make fail-time reporting as useful as possible. Async stacktraces, source maps, etc.

### PR DESCRIPTION
**Pull request by SomeHats**
- All errors for http response code are now `instanceof HttpError`
- Stack traces are longer, filter out node internal calls, and preserve the stack across async operations
- Any error occurring within an express handler is logged - no more `.catch(err => { console.error(err); throw err })`
- `setup()` now takes a `bugsnagIgnore` option to prevent some classes of error from being reported to bugsnag

WOOP

Closes #3

### CODE REVIEW

**Comment by jgwmaxwell** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/musicglue/mg-express/pull-request/5/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=musicglue/mg-express)

File: src/index.js [hunk 1]
```diff
@@ -9,6 +11,8 @@ import uuid from 'node-uuid';
 import logger from './logger';
 import errorHandler from './error-handler';
 
+Error.stackTraceLimit = Infinity;
```
Comment (jgwmaxwell) [inline src/index.js]: Not sure this is a good idea - what about 1k?

File: src/index.js [hunk 2]
```diff
@@ -40,6 +45,15 @@ export default (options) => {
     },
   });
 
+  if (config.bugsnag) bugsnag.onBeforeNotify(notification => {
+    const event = notification.events[0];
```
Comment (jgwmaxwell) [inline src/index.js]: `const [event] = notification.events;`
`const [error] = event.exceptions;`

File: src/index.js [hunk 3]
```diff
@@ -40,6 +45,15 @@ export default (options) => {
...
+    const error = event.exceptions[0];
+    if (config.bugsnagIgnore.includes(error.errorClass)) {
```
Comment (jgwmaxwell) [inline src/index.js]: `return !config.bugsnagIgnore.includes(error.errorClass);` ?

**Comment by freesteph** [comment]
Approved 📖
